export const pricing = {
  meta: {
    title: "Paketi i cijene — web stranice, shopovi, AI, održavanje | Flomis",
    description:
      "Transparentne cijene izrade web stranica, web shopova, AI asistenata i održavanja. Fiksna ponuda, bez skrivenih troškova. Flomis, Osijek.",
  },
  label: "Paketi i cijene",
  title: ["Jasne cijene.", "Bez sitnih slova."],
  lead:
    "Ovo su okvirni paketi. Nakon kratkog razgovora dobiješ fiksnu ponudu — i ta cijena se ne mijenja. Sve cijene su bez PDV-a.",
  note: "Cijene paketa su okvirne — točan iznos ovisi o opsegu i dobiva se u fiksnoj ponudi.",
  groups: [
    {
      id: "web",
      title: "Web stranice",
      text: "Prezentacijske stranice za firme, obrte i profesionalce.",
      plans: [
        {
          name: "Start",
          price: "500 €",
          period: "jednokratno",
          tagline: "Za obrte i male firme kojima treba profesionalna prisutnost.",
          features: [
            "Do 5 stranica",
            "Dizajn po mjeri",
            "Mobilna optimizacija",
            "Kontakt forma i mapa",
            "Osnovni SEO",
            "30 dana podrške",
          ],
          cta: "Zatraži ponudu",
          highlighted: false,
        },
        {
          name: "Business",
          price: "1.200 €",
          period: "jednokratno",
          tagline: "Za firme koje žele stranicu koja aktivno donosi upite.",
          features: [
            "Do 12 stranica",
            "Dizajn po mjeri + animacije",
            "CMS za samostalno uređivanje",
            "Napredni SEO i strukturirani podaci",
            "Blog / novosti",
            "Višejezičnost (opcija)",
            "Analitika i ciljevi",
            "60 dana podrške",
          ],
          cta: "Zatraži ponudu",
          highlighted: true,
          badge: "Najpopularniji",
        },
        {
          name: "Custom",
          price: "Po dogovoru",
          period: "",
          tagline: "Kompleksni projekti, portali, integracije s vanjskim sustavima.",
          features: [
            "Neograničen broj stranica",
            "Custom funkcionalnosti",
            "Integracije (ERP, CRM, API)",
            "Korisnički računi",
            "Dedicirani projektni voditelj",
            "SLA podrška",
          ],
          cta: "Dogovori razgovor",
          highlighted: false,
        },
      ],
    },
    {
      id: "shop",
      title: "Web shopovi",
      text: "Online trgovine spremne za hrvatsko tržište.",
      plans: [
        {
          name: "Shop Start",
          price: "1.000 €",
          period: "jednokratno",
          tagline: "Za početak online prodaje, do 100 proizvoda.",
          features: [
            "Shopify ili WooCommerce",
            "Dizajn po mjeri",
            "Kartično plaćanje + pouzeće",
            "Integracija dostave",
            "Uvoz do 100 proizvoda",
            "Obuka za vođenje shopa",
          ],
          cta: "Zatraži ponudu",
          highlighted: false,
        },
        {
          name: "Shop Pro",
          price: "2.000 €",
          period: "jednokratno",
          tagline: "Za ozbiljnu prodaju s automatizacijom i marketingom.",
          features: [
            "Sve iz Shop Start",
            "Neograničen broj proizvoda",
            "Automatski e-mailovi i napuštena košarica",
            "Kuponi, akcije, varijante",
            "Fiskalizacija / računovodstvo",
            "SEO struktura proizvoda",
            "90 dana podrške",
          ],
          cta: "Zatraži ponudu",
          highlighted: true,
          badge: "Preporuka",
        },
        {
          name: "Shop Custom",
          price: "Po dogovoru",
          period: "",
          tagline: "B2B shopovi, ERP integracije, multi-brand, marketplace.",
          features: [
            "Custom platforma",
            "ERP / skladište integracija",
            "B2B cjenici i računi",
            "Višejezično, više valuta",
            "Dedicirani tim",
          ],
          cta: "Dogovori razgovor",
          highlighted: false,
        },
      ],
    },
    {
      id: "ai",
      title: "AI asistenti",
      text: "Postavljanje jednokratno + mjesečno održavanje i AI troškovi.",
      plans: [
        {
          name: "AI Web",
          price: "200 €",
          period: "postavljanje + 39 €/mj",
          tagline: "Asistent na web stranici, treniran na tvojim podacima.",
          features: [
            "Baza znanja iz tvojih materijala",
            "Chat widget na web stranici",
            "Prikupljanje upita na e-mail",
            "Do 500 razgovora mjesečno",
            "Mjesečno poboljšanje odgovora",
          ],
          cta: "Zatraži demo",
          highlighted: false,
        },
        {
          name: "AI Omni",
          price: "450 €",
          period: "postavljanje + 79 €/mj",
          tagline: "Web + WhatsApp + Messenger, zakazivanje i CRM.",
          features: [
            "Sve iz AI Web",
            "WhatsApp i Messenger",
            "Zakazivanje termina u kalendar",
            "Slanje upita u CRM",
            "Do 2.000 razgovora mjesečno",
            "Eskalacija prema čovjeku",
          ],
          cta: "Zatraži demo",
          highlighted: true,
          badge: "Najveća ušteda",
        },
      ],
    },
    {
      id: "care",
      title: "Hosting i održavanje",
      text: "Mjesečno, bez ugovorne obveze. Otkaz bilo kad.",
      plans: [
        {
          name: "Hosting",
          price: "90 €",
          period: "godišnje",
          tagline: "Brz hosting u EU, domena, SSL i backupi.",
          features: [
            "EU hosting + CDN",
            "Domena (.hr / .com)",
            "SSL certifikat",
            "Dnevni backupi",
            "Nadzor dostupnosti",
          ],
          cta: "Naruči",
          highlighted: false,
        },
        {
          name: "Care",
          price: "39 €",
          period: "mjesečno",
          tagline: "Održavanje za stranice koje se rijetko mijenjaju.",
          features: [
            "Sve iz Hostinga",
            "Tjedne sigurnosne nadogradnje",
            "2 sata izmjena mjesečno",
            "Mjesečni izvještaj",
            "Podrška e-mailom (24h)",
          ],
          cta: "Naruči",
          highlighted: true,
          badge: "Bez brige",
        },
        {
          name: "Care Plus",
          price: "79 €",
          period: "mjesečno",
          tagline: "Za shopove i stranice s čestim izmjenama.",
          features: [
            "Sve iz Care",
            "6 sati izmjena mjesečno",
            "Praćenje brzine i optimizacija",
            "Prioritetna podrška (telefon)",
            "Kvartalni pregled i prijedlozi",
          ],
          cta: "Naruči",
          highlighted: false,
        },
      ],
    },
  ],
  compare: {
    title: "Nisi siguran koji paket?",
    text: "Pošalji nam par rečenica o firmi i cilju. Preporučimo paket koji ima smisla — i reći ćemo ako ti treba manje nego što misliš.",
    cta: { label: "Pomozite mi odabrati", href: "/kontakt" },
  },
  faqLabel: "FAQ",
  faqTitle: "Pitanja o cijenama.",
  groupsNav: "Grupe paketa",
  faq: [
    {
      q: "Jesu li cijene fiksne?",
      a: "Da. Nakon razgovora dobiješ ponudu s fiksnom cijenom i rokom. Ako se opseg mijenja tijekom projekta, dogovorimo to unaprijed — nikad naknadno na računu.",
    },
    {
      q: "Kako ide plaćanje?",
      a: "Obično 40% avans, 60% po lansiranju. Za veće projekte moguće je plaćanje u fazama. Održavanje i hosting se plaćaju mjesečno ili godišnje.",
    },
    {
      q: "Mogu li kasnije nadograditi paket?",
      a: "Naravno. Sve gradimo tako da se može proširiti. Nadogradnja s Start na Business, ili dodavanje AI asistenta, ide bez ponovnog rada.",
    },
    {
      q: "Što nije uključeno u cijenu?",
      a: "Fotografiranje, plaćeni oglasi, licence trećih strana (npr. Shopify pretplata) i pisanje većih količina sadržaja — osim ako nije izričito navedeno u ponudi.",
    },
  ],
} as const;
